// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qypazgkngxhazgkuevwq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5cGF6Z2tuZ3hoYXpna3VldndxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNTY4NjUsImV4cCI6MjA3NDYzMjg2NX0.3NgO6VJFYn143_qgl_UncfWpTDmA4hVV85zXneOeMxo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});